language: node_js
node_js:
- lts/*
cache:
  directories:
    - node_modules
env:
  global:
    - DB_USER=valp1
    - DB_PASSWORD=azevbn123
    - GOOGLE_CLIENT=979187681926-as6gk94f9pfhl2ob739rjn8lhnk37oqv.apps.googleusercontent.com
    - GOOGLE_SECRET=5G2oDzh8i21_-qY6z6j7iKFI
    - VALP_SECRET=e7e4b966a611af9_-cb23c9672fcf50579505929ec
deploy :
  provider: heroku
  app: valparaiso-mockup
  api_key:
    secure: IPQe4koLQT9a+iTA2mQ5IeNX9m0WSu6wHRpVEmDH8Hy6VlofdAZKfxULVbY4sS/dP4qNz/nJebrNrT4+T7mKjFyPpqQ2AmM1hKjp6wUj2bbGBAa0ZBEunlgu7yL2Jl3fJxBiTMVDvIZYec3t+u2Nzub2n3qNmLkZzjWh1rbxKqHemMde+qOv6JrPPtC/cuj7BsuiNdP/vj/9p1U2b3g2zaEeBlcO89L5cNwF1NZ3553daDOwF9Aej9WrsSAVxhJ2s6l5RlpsjrX1he6wNuvJT2S+Vt9uvlFFYO8DVXI2ApoGfaNJ4ih6AStmuZNEhXU/P180CVE4+OWGG6G9nefcZSiStSs2V5hOle2rnvOm6XWd5jqAGwYctj6p2cfouEZnK53pz0ybCCMK0GHxXuZF29QO6DMbed5zKgIMLEy0JBzImf3XJLRcCEUPUWdNCGVr8dIkrMEgfV64p6pdN+CLeeUJ2GtnXUnRoccY5D6aRnvjgFef6Xg4vTJoAxOK5fdZR5sgxQfEnlBjSMHKT0h5Tbi73S0lOq6JQkP+ztD7X2ARO2b8R9eqFnrRvDMVvnTFWDnEwIvlLw4ieds3mp0FVy2R64S7BxSVpJjkhNTzz2BZuW+Af1+5nv6p39kkN/ivrR2bZpvMwLUJj8qpRGnrxm9Bk+h2WowMkQ+yXYJtDfU=
